builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm

archives:
  - format: tar.gz
    name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
snapshot:
  name_template: "{{ incpatch .Version }}-next"
release:
  draft: true
